### ISSUE TITLE
SpecialDates not showing with Binding

### ISSUE THREAD

**Issue by allistoncarlos** [rebeccaXam/XamForms.Controls.Calendar#36]
I'm using MVVMLight for Bindings, and in the AttendancesPage.xaml I have:

```xaml
<controls:Calendar x:Name="Calendar" SpecialDates="{Binding Attendances}" 
	Padding="10,0,10,0" 
	StartDay="Sunday" 
	SelectedBorderWidth="1" 
	DisabledBorderColor="Black">
</controls:Calendar>
```

Using my AttendanceViewModel, with the following code:

```csharp
#region Private Fields
private ObservableCollection<SpecialDate> attendances;
#endregion

#region Dependency Properties
private const string AttendancesPropertyName = "Attendances";
#endregion

#region Properties
public ObservableCollection<SpecialDate> Attendances
{
	get { return attendances; }
	set { Set(AttendancesPropertyName, ref attendances, value); }
}
#endregion

#region Private Fields
private readonly IWorkoutService workoutService;
private readonly UserModel authUser;
#endregion

#region Constructor
public AttendanceViewModel(IWorkoutService workoutService, UserModel authUser)
{
	this.workoutService = workoutService;
	this.authUser = authUser;
}
#endregion

#region IPageLifecicleEvents
public async Task OnAppearing()
{
	IsBusy = true;

	var dates = new List<SpecialDate>();

	var specialDate = new SpecialDate(new DateTime(2017, 03, 13));
	specialDate.BackgroundColor = Color.Green;
	specialDate.TextColor = Color.White;

	dates.Add(specialDate);

	Attendances = new ObservableCollection<SpecialDate>(dates);

	IsBusy = false;
}
#endregion
```

When I set Attendances property, the Calendar doesn't change. If I use the same OnAppearing method on AttendancesPage.xaml.cs, it works...

How can I use Binding to show SpecialDates on Calendar?

**Comment by rebeccaXam** [comment]
The binding is not working because the type of ``SpecialDate`` is ``List<SpecialDate>`` and not ``ObservableCollection<SpecialDate>``. 

In version 1.1.0 ``SpecialDate`` is of type ``ICollaction<SpecialDate>`` so you  should be able to use ObservableCollection with that version. 

*Note: I choose List<SpecialDate> because some people will add 100 and more dates and when a ObservableCollection is used ever add will trigger a redraw. With a list you can add all the items first and then use calendar.RaiseSpecialDatesChanged() to trigger a redraw ones*
