### ISSUE TITLE
Random Crashes on Android // Xamarin.Forms

### ISSUE THREAD

**Issue by ValonK** [rebeccaXam/XamForms.Controls.Calendar#47]
Hello, 

sometimes I get completely random crashes, the problem is that I can't debug them or fix them because I have no clue where to start.
Here's a StackTrace from Mobile Center. 

Xamarin.Forms / happens only on Android.

```
ThrowHelper.ThrowInvalidOperationException (System.ExceptionResource resource)
List`1+Enumerator[T].MoveNextRare ()
List`1+Enumerator[T].MoveNext ()
Enumerable.TryGetFirst[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate, System.Boolean& found)
Enumerable.FirstOrDefault[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate)
Calendar+<ChangeCalendar>c__AnonStorey7.<>m__0 ()
Thread+RunnableImplementor.Run ()
IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this)
(wrapper dynamic-method) System.Object:71e19f9c-e626-431a-8741-76f2e9d766a8 (intptr,intptr)
```

Does anyone experience something like this?

**Comment by rebeccaXam** [comment]
Hello, 

it seems as if the exception comes from ``ChangeCalendar`` method in ``Calendar.cs`` from the method ``FirstOrDefault``. The only use of this method is 
```sd = SpecialDates.FirstOrDefault(s => s.Date.Date == start.Date);```

So it seems as if the ``SpecialDates`` list is change will the the render method is running, List are not thread safe which is why you probably getting this exception (ThrowInvalidOperationException => Collection was modified).

By default the ``SpecialDates`` list is a ``List<SpecialDate>``, but it can be everything that implements ``ICollection<T>``. Either you do not add SpecialDate when ``calendar.Content == null`` (then the calendar is drawn) or use a Thread safe List.

I do not use a Thread safe list by default, because it needs to clone the list every time a iterator is use (which can impact memory and performance very heavily).

Hoop this helps ;)

**Comment by ValonK** [comment]
Thanks for the Help I will try that and let you know!

**Comment by KerosenoDev** [comment]
It has not worked for me :(

**Comment by KerosenoDev** [comment]
> Hello,
> 
> it seems as if the exception comes from `ChangeCalendar` method in `Calendar.cs` from the method `FirstOrDefault`. The only use of this method is
> `sd = SpecialDates.FirstOrDefault(s => s.Date.Date == start.Date);`
> 
> So it seems as if the `SpecialDates` list is change will the the render method is running, List are not thread safe which is why you probably getting this exception (ThrowInvalidOperationException => Collection was modified).
> 
> By default the `SpecialDates` list is a `List<SpecialDate>`, but it can be everything that implements `ICollection<T>`. Either you do not add SpecialDate when `calendar.Content == null` (then the calendar is drawn) or use a Thread safe List.
> 
> I do not use a Thread safe list by default, because it needs to clone the list every time a iterator is use (which can impact memory and performance very heavily).
> 
> Hoop this helps ;)

It has not worked for me :(
